apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cd-pipeline-run
spec:
  pipelineRef:
    name: cd-pipeline
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipelinerun-pvc
  params:
    - name: repo-url
      value: "https://github.com/<your-username>/accounts.git"
    - name: branch
      value: main
    - name: build-image
      value: "image-registry.openshift-image-registry.svc:5000/<namespace>/accounts:1.0"
